# Config file for Air
[build]
  #cmd = "go build -o tmp\\main.exe ."  # Use Windows path
  #bin = "tmp\\main.exe"
  #full_bin = "tmp\\main.exe"  # Corrected Windows path

  cmd = "go build -o tmp/main.exe ."  # Use Windows path
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"  # Corrected Windows path
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  delay = 200


[log]
  time = true
  level = "debug"

[serve]
  watch_dir = ["."]
  restart = true
  kill_delay = "1s"

[screen]
  clear = true
